name: Build Vncheat Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        run: |
          export THEOS=$HOME/theos
          git clone --depth 1 https://github.com/theos/theos.git $THEOS
          # Cài đặt ldid để ký file, tránh văng game
          brew install ldid
          
      - name: Setup SDK
        run: |
          export THEOS=$HOME/theos
          mkdir -p $THEOS/sdks
          curl -LO https://github.com/theos/sdks/archive/master.tar.gz
          tar -xf master.tar.gz -C $THEOS/sdks --strip-components=1

      - name: Fix Missing dm.pl
        run: |
          # Tải công cụ đóng gói dm.pl vào hệ thống
          curl -LO https://raw.githubusercontent.com/theos/theos/master/bin/dm.pl
          mv dm.pl $HOME/theos/bin/
          chmod +x $HOME/theos/bin/dm.pl

      - name: Compile Vncheat Dylib
        run: |
          export THEOS=$HOME/theos
          # CHỈ ĐƯỜNG DẪN: Chui vào folder template trước khi build
          cd template
          make package FINALPACKAGE=1
          
      - name: Upload Vncheat Product
        uses: actions/upload-artifact@v4
        with:
          name: Vncheat-Dylib-Package
          # Chỉ định đường dẫn file kết quả nằm trong folder template
          path: template/packages/*.deb
